---
- name: Set up gentoo laptop
  hosts: laptop
  gather_facts: true
  become: yes
  tasks:
  - import_role:
      name: gentoo-services-ctl
    when:
    #- ansible_distribution == 'Gentoo'
    - ansible_distribution != 'MacOSX'
  - import_role:
      name: gentoo-apps
    when:
    #- ansible_distribution == 'Gentoo'
    - ansible_distribution != 'MacOSX'
  - import_role:
      name: macos-apps
    become: false
    when:
    - ansible_distribution == 'MacOSX'
