---

- name: Create config folder for unmasked ebuilds
  ansible.builtin.file:
    path: >-
      {{ gentoo_prefix }}/etc/portage/package.unmask
    state: directory

- name: Unmask {{ package_name }}
  ansible.builtin.copy:
    content: >-
      {{ package_name }}
    dest: >-
      {{ gentoo_prefix }}/etc/portage/package.unmask/{{
        package_name | replace('/', '--')
      }}--managed

...
