--- # vim:se ft=ansible:
- name: Put Awesome WM enabled .xinitrc config in place
  template:
    src: xinitrc-template
    dest: ~/.xinitrc
- name: Create Awesome WM config dir within userspace
  file:
    dest: ~/.config/awesome
    state: directory
- name: Get Awesome WM widgets into config dir  # noqa 401
  git:
    clone: yes
    dest: ~/.config/awesome/awesome-wm-widgets
    recursive: yes
    repo: https://github.com/streetturtle/awesome-wm-widgets.git
    update: yes
- name: Install bit32 lua lib
  become: yes
  become_user: root
  command: luarocks install bit32
  args:
    creates: /usr/lib64/lua/luarocks/lib/lua/5.1/bit32.so
- name: Ensure that bit32 from luarocks is linked under user dir
  file:
    src: /usr/lib64/lua/luarocks/lib/lua/5.1/bit32.so
    dest: ~/.config/awesome/bit32.so
    state: link
- name: Put Awesome WM resource script in place
  template:
    src: awesome-rc.lua-template
    dest: ~/.config/awesome/rc.lua
- name: Create Redshift config dir within userspace
  file:
    dest: ~/.config/redshift
    state: directory
- name: Put Redshift config in place
  template:
    src: redshift.conf.j2
    dest: ~/.config/redshift/redshift.conf
