--- # vim:se ft=ansible:
- name: Ensure that Ansible dev env is set up
  import_tasks: ansible.yml
- name: Ensure that SSH is configured
  import_tasks: ssh.yml
- name: Ensure that Git is configured
  import_tasks: git.yml
- name: Ensure that NeoVim is configured
  import_tasks: neovim.yml
- name: Ensure that GTK is configured
  import_tasks: gtk.yml
- name: Ensure that kitty is configured
  import_tasks: kitty.yml
- name: Ensure that Oh My ZSH is configured
  import_tasks: omz.yml
- name: Ensure that userspace Pythons are set up with pyenv
  import_tasks: pyenv.yml
- name: Ensure that NodeJS is configured with nvm
  import_tasks: nvm.yml
- name: Ensure that Awesome WM is configured
  import_tasks: awesome.yml
  tags:
  - awesome-wm
  when:
  #- ansible_distribution == 'Gentoo'
  - ansible_distribution != 'MacOSX'
- name: Ensure that Hyprland is configured
  import_tasks: hyprland.yml
  tags:
  - hyprland
  when:
  - ansible_distribution != 'MacOSX'
- name: Ensure that source code projects are in place
  import_tasks: src.yml
- name: Ensure that Fedora Project is configured
  import_tasks: fedoraproject.yml
  when:
  - ansible_distribution != 'MacOSX'
- name: Ensure systemd services are enabled
  ansible.builtin.command:
    argv:
    - systemctl
    - --user
    - enable
    - --now
    - >-
      {{ item }}
  failed_when: false
  loop:
  - kbfs  # Keybase filesystem
  - keybase
  - pipewire-pulse.socket
  - wireplumber
  when:
  - ansible_distribution != 'MacOSX'
