--- # vim:se ft=ansible:
- name: Get oh-my-zsh onto machine  # noqa 401
  git:
    clone: yes
    dest: ~/.oh-my-zsh
    recursive: yes
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    update: yes
- name: Copy own oh-my-zsh custom extensions onto machine  # noqa 401
  copy:
    dest: ~/.oh-my-zsh/custom/
    src: oh-my-zsh/
- name: Get oh-my-zsh custom plugins onto machine  # noqa 401
  git:
    clone: yes
    dest: ~/.oh-my-zsh/custom/plugins/{{ item.key }}
    recursive: yes
    repo: "{{ item.value }}"
    update: yes
  with_dict: "{{ oh_my_zsh.custom_plugins }}"
- name: Get oh-my-zsh custom themes onto machine  # noqa 401
  git:
    clone: yes
    dest: ~/.oh-my-zsh/custom/themes/{{ item.key }}
    recursive: yes
    repo: "{{ item.value }}"
    update: yes
  with_dict: "{{ oh_my_zsh.custom_themes }}"
- name: Symlink oh-my-zsh custom themes
  file:
    src: ~/.oh-my-zsh/custom/themes/{{ item.key }}/{{ item.key }}.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/{{ item.key }}.zsh-theme
    state: link
  with_dict: "{{ oh_my_zsh.custom_themes }}"
- name: Put oh-my-zsh enabled .zshrc config in place
  template:
    src: zshrc.zsh-template
    dest: ~/.zshrc
