---
- name: Install xcode
  become: true
  shell: |
    os=$(sw_vers -productVersion | awk -F. '{print $1 "." $2}')
    if softwareupdate --history | grep --silent "Command Line Tools.*${os}"; then
        echo 'Command-line tools already installed.' 
    else
        echo 'Installing Command-line tools...'
        in_progress=/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
        touch ${in_progress}
        product=$(softwareupdate --list | awk "/\* Command Line.*${os}/ { sub(/^   \* /, \"\"); print }")
        softwareupdate --verbose --install "${product}" || echo 'Installation failed.' 1>&2 && rm ${in_progress} && exit 1
        rm ${in_progress}
        echo 'Installation succeeded.'
    fi

- name: Install apps via brew
  homebrew:
    name:
    - asciinema
    - fira-code
    - fzf
    - git
    - keybase
    - kitty
    - neovim
    - tmux
    - yubikey-manager
